### ISSUE TITLE
Display leaderboard after player finishes a game, and highlight their score

### ISSUE THREAD

**Issue by mwcz** [redhataccess/engage-game#28]
So we can display the leaderboard after a player plays

**Comment by Jared-Sprague** [comment]
I'm going to make a separate issue for displaying the leaderboard after playing

**Comment by Jared-Sprague** [comment]
We should make their score high-lighted so they can easiliy see where they placed.

**Comment by Jared-Sprague** [comment]
This is related to #31

**Comment by Jared-Sprague** [comment]
I had an idea we can accomplish this with the current leaderboard.  Since we don't have a dedicated leaderboard screen this time, we don't need to pull the leaderboard stats evey 15 seconds.  We can just pull it everytime the leaderboard is displayed.  That way they will see the cool flipping animation when it switches to the leaderboard if they got on it.

**Comment by mwcz** [comment]
Nice!  That's a great idea.
